name: Notify Teams - New Issue
description: |
  A GitHub Action that notifies of a new Issue via Microsoft Teams.
inputs:
  secrets:
    incoming_webhook: Public URL of the Microsoft Teams incoming webhook.
    required: true

outputs: ~
runs:
  using: "composite"
  steps:
    - name: Send notification to Teams
      using: aliencube/microsoft-teams-actions@7af536b59221419054c51e25db4dd180915acb46
      with:
        title: "New issue opened"
        summary: "title: ${{ github.event.issue.title }}"
        text: "title: ${{ github.event.issue.title }}"
        theme_color: "#00ccff"
        actions: '[{ "@type": "OpenUri", "name": "View issue", "targets": [{ "os": "default", "uri": "${{ github.event.issue.resourcePath }}" }]}]'
        webhook_uri: ${{ secrets.incoming_webhook }}
